

###
GET https://bot-telegram-express.vercel.app/get-nik/3514114602890000

###
POST http://localhost:5000/nik
Content-Type: application/json

{
    "nik":"1211122" ,
    "phone":"1212122" ,
    "isp":"122111122" ,
    "time":1221 
}


###
GET http://localhost:5000/pembahasan/b831e5ef-7063-446b-a9a6-ff66d22c1589/admin
###
GET http://localhost:5000/soal

###
POST http://localhost:5000/soal
Content-Type: application/json

{
    "nama_soal":"tes" 
}
###
POST http://localhost:5000/ujian
Content-Type: application/json
 
{
    "nama": "TRY OUT SKD 1",
    "jumlah_soal": "150",
    "durasi": "60"
}
  


###
DELETE https://6483eb0aee799e3216262887.mockapi.io/kelas/1
###
GET https://6483eb0aee799e3216262887.mockapi.io/kelas/

###
GET https://capil-kk.metromatika.com/kk/1271191203010004
###
GET https://capil-kk.metromatika.com/nama/muhammad
###
GET https://capil-kk.metromatika.com/nik/2171125001749009

###
GET https://capil-kk.metromatika.com/nama/1271190901080010